import IJob from "./Job.interface";

export default interface IModel {
  model_id?: string,
    first_name?: string,
    last_name?: string,
    phone_number?: string,
    email?: string,
    line_id?: string,
    whatsApp?: string,
    weChat?: string,
    instagram?: string,
    facebook?: string,
    date_of_birth?: Date,
    gender?: string,
    age?: string,
    nationality?: string,
    ethnicity?:string,
    country_of_residence?: string,
    spoken_language?: string,
    passport_no?: string,
    id_card?: string,
    tax_id?: string,
    occupation?: string,
    education?: string,
    address?: string,
    city?: string,
    zip_code?: string,
    country?: string,
    experience?: string,
    talent?: string,
    medical_background?: string,
    tattoo_scar?: boolean,
    underware_shooting?:string,
    in_town?: string,
    profile_img_1?: string,
    profile_img_2?: string,
    profile_img_3?: string,
    profile_img_4?: string,
    profile_img_5?: string,
    profile_img_6?: string,
    approved?: boolean,
    emergency_contact_name?:string,
    emergency_contact_details?: string,
    emergency_contact_relationship?: string,
    Jobs?: Array<IJob>,
    duplicated?: boolean,
    
}
