 import {Model} from 'sequelize'
 export default interface ModelInstance extends Model {
    model_id?: string,
      first_name: string,
      last_name: string,
      phone_number?: string,
      email?: string,
      line_id?: string,
      whatsApp?: string,
      weChat?: string,
      instagram?: string,
      facebook?: string,
      date_of_birth: Date,
      gender: string,
      age?: string,
      nationality?: string,
      ethnicity?:string,
      country_of_residence?: string,
      spoken_language?: string,
      passport_no?: string,
      id_card?: string,
      tax_id?: string,
      occupation?: string,
      education?: string,
      address?: string,
      city?: string,
      zip_code?: string,
      country?: string,
      experience?: string,
      talent?: string,
      medical_background?: string,
      tattoo_scar?: boolean,
      underware_shooting?: boolean,
      in_town?: boolean,
      profile_img?: string,
      approved?: boolean
}
